export enum MetricIds {
  DATA_IMPORTER_ERROR = 'DATA_IMPORTER_ERROR',

  // FIRST FETCH
  FIRST_DATA_FETCH = 'FIRST_DATA_FETCH',
  FIRST_DATA_FETCH_FAIL = 'FIRST_DATA_FETCH_FAIL',
  FIRST_DATA_FETCH_NO_DATA = 'FIRST_DATA_FETCH_NO_DATA',
  FIRST_DATA_FETCH_SUCCESS = 'FIRST_DATA_FETCH_SUCCESS',

  // FIBIT IMPORTER
  FITBIT_IMPORTER = 'FITBIT_IMPORTER',
  FITBIT_IMPORTER_ERROR = 'FITBIT_IMPORTER_ERROR',
  FITBIT_IMPORTER_STARTED = 'FITBIT_IMPORTER_STARTED',
  FITBIT_IMPORTER_SUCCESS = 'FITBIT_IMPORTER_SUCCESS',

  // GMAIL IMPORTER
  GMAIL_PURCHASED_IMPORTER = 'GMAIL_PURCHASED_IMPORTER',
  GMAIL_PURCHASED_IMPORTER_ERROR = 'GMAIL_PURCHASED_IMPORTER_ERROR',
  GMAIL_PURCHASED_IMPORTER_STARTED = 'GMAIL_PURCHASED_IMPORTER_STARTED',
  GMAIL_PURCHASED_IMPORTER_SUCCESS = 'GMAIL_PURCHASED_IMPORTER_SUCCESS',

  SCHEDULE_DATA_FETCH = 'SCHEDULE_DATA_FETCH',

  // VENMO IMPORTER
  VENMO_IMPORTER = 'VENMO_IMPORTER',
  VENMO_IMPORTER_ERROR = 'VENMO_IMPORTER_ERROR',
  VENMO_IMPORTER_STARTED = 'VENMO_IMPORTER_STARTED',
  VENMO_IMPORTER_SUCCESS = 'VENMO_IMPORTER_SUCCESS',
}

export enum LogTypes {
  DEBUG = 'debug',
  ERROR = 'error',
  INFO = 'info',
  LOG = 'log',
}
